project:
  type: website
  output-dir: docs


website:
  title: "Arzoo Gupta - MUSA 5080 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Labs
        menu: 
          - href: Labs/Lab_0/lab0_template.qmd
            text: Lab 0
          - href: Labs/Lab_1/lab1_template.qmd
            text: "Lab 1: Census Data Quality for Policy Decisions"
      
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
